name: dispatch and call

# Demo to show that inputs in workflow dispatch and workflow call could be used together.

on:
  repository_dispatch:
    types: [repository_workflow_together]
  workflow_dispatch:
    inputs:
      hello-msg:
        description: "Hello Message"
        type: string
        required: false
        default: ${{ github.event.client_payload.hello-msg }}
      is-exist:
        description: "Is Exist"
        type: boolean
        required: false
        default: ${{ github.event.client_payload.is-exist }}

jobs:
  dispatch-and-call-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: |
          echo "Hello msg: ${{github.event.inputs.hello-msg}}, exist: ${{github.event.inputs.is-exist}}"
      
