name: release
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLOUDSMITH_USER:
        required: true
      CLOUDSMITH_API_KEY:
        required: true

jobs:
  release:
    name: release kb-oss-parent
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup git user
        env:
          BUILD_USER: ${{ secrets.BUILD_USER }}
          BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
        run: |
          git config --global user.email "xsalefter@xsalefter.id"
          git config --global user.name "xsalefter"
          git config --global url."https://${BUILD_USER}:${BUILD_TOKEN}@github.com/".insteadOf "git@github.com:"
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup Maven Setting XML
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "cloudsmith", "username": "${{ secrets.CLOUDSMITH_USER }}", "password": "${{ secrets.CLOUDSMITH_API_KEY }}"}]'
      - name: Pull and Build Project
        run: |
          git pull origin master
          mvn --errors --batch-mode --show-version clean install
      - name: Deploy artifacts
        run: mvn release:clean release:prepare release:perform