name: update-version

on:
  workflow_call:

# No matter how "neat" to have this, accessing variables in GitHub action always inconsistent. See:
# https://github.com/actions/runner/issues/2372
# https://github.com/actions/runner/issues/1189
# https://www.google.com/search?q=Unrecognized+named-value%3A+%27env%27.
# Lets save our sanity and abandon this.
# env:
# POM_PROPERTY_NAME: ${{github.event.client_payload.property_name}}
# POM_PROPERTY_VALUE: ${{github.event.client_payload.property_value}}

jobs:
  updating_version:
    runs-on: ubuntu-22.04
    if: github.event.client_payload.property_name != '' && 
        github.event.client_payload.property_value != '' && 
        contains(fromJSON('["kb-commons.version", "kb-base.version"]'), github.event.client_payload.property_name)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Repository Dispatch Webhook Values
        run: |
          echo github.event.client_payload.property_name  : ${{github.event.client_payload.property_name}}
          echo github.event.client_payload.property_value : ${{github.event.client_payload.property_value}}
      - name: Setup git user
        env:
          BUILD_USER: ${{ secrets.BUILD_USER }}
          BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
        run: |
          git config --global user.email "xsalefter@xsalefter.id"
          git config --global user.name "xsalefter"
          git config --global url."https://${BUILD_USER}:${BUILD_TOKEN}@github.com/".insteadOf "git@github.com:"
      - name: Install XML Starlet
        run: sudo apt-get install xmlstarlet
      - name: Update ${{github.event.client_payload.property_name}} in pom.xml file
        run: xmlstarlet ed --inplace -N x="http://maven.apache.org/POM/4.0.0" -u "//x:properties/x:${{github.event.client_payload.property_name}}" -v ${{github.event.client_payload.property_value}} pom.xml
      - name: Commit Up To Date pom.xml
        run: |
          git add pom.xml
          git commit -m "[github-action] update ${{github.event.client_payload.property_name}} value to ${{github.event.client_payload.property_value}}"
          git push origin master
